# Generated by Django 5.2.7 on 2025-10-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_brand_alter_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='photos',
            field=models.ImageField(blank=True, null=True, upload_to='cars/'),
        ),
    ]
