# Generated by Django 5.2.7 on 2025-12-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_bio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='bio',
            new_name='Descrição',
        ),
    ]
