# Generated by Django 5.2.7 on 2025-12-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_rename_bio_car_descrição'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='Descrição',
            new_name='bio',
        ),
    ]
